# Generated by Django 3.0.2 on 2020-02-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='numrooms',
            new_name='no_of_rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='area',
        ),
    ]
